### ISSUE TITLE
TypeError: solve() got an unexpected keyword argument 'async'

### ISSUE THREAD

**Issue by th-char** [Aluriak/clyngor#29] opened 2022-01-23 16:45 UTC
Hi, when I run the following program as given as an official example
```
from clyngor import solve

answers = solve(inline="""
rel(a,(c;d)). rel(b,(d;e)).
obj(X):- rel(X,_) ; rel(X,Y): att(Y).
att(Y):- rel(_,Y) ; rel(X,Y): obj(X).
:- not obj(X):obj(X).
:- not att(Y):att(Y).
""")

for answer in answers:
  print(answer)
```
I get the following error 
```
Traceback (most recent call last):
  File "clyngor_example.py", line 11, in <module>
    for answer in answers:
  File "/home/theo/.local/lib/python3.8/site-packages/clyngor/answers.py", line 205, in __iter__
    for answer_set, optimization, optimality, answer_number in self._answers:
  File "/home/theo/.local/lib/python3.8/site-packages/clyngor/answers.py", line 327, in __compute_answers
    with self._solver.solve(**kwargs) as models:
TypeError: solve() got an unexpected keyword argument 'async'
```
I've tried setting `use_clingo_module=False` and specifying `clingo_bin_path` as suggested in another issue, but this gives me the error 

```
Traceback (most recent call last):
  File "/home/theo/.local/lib/python3.8/site-packages/clyngor/parsing.py", line 197, in parse_clasp_output
    line = next(output)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "clyngor_example.py", line 11, in <module>
    for answer in answers:
  File "/home/theo/.local/lib/python3.8/site-packages/clyngor/answers.py", line 205, in __iter__
    for answer_set, optimization, optimality, answer_number in self._answers:
  File "/home/theo/.local/lib/python3.8/site-packages/clyngor/solving.py", line 208, in _gen_answers
    for ptype, payload in parse_clasp_output(stdout, yield_stats=True):
RuntimeError: generator raised StopIteration
```

Please let me know if you have any suggestions on how I can get this example working. Thank you in advance

**Platform:**
Clyngor version: f3f38b72b0496ca8b6d6f7d14e1a8691773c8ecf (head of master at time of writing)
Clingo version: clingo 3.0.5 (clasp 1.3.10)
Python version: Python 3.8.10

**Comment by Aluriak** [comment] 2022-01-24 00:05
Hi !

Your second output suggests that clingo didn't produced any parsable output.

Also, i can't reproduce your problem with python 3.9 and the same clyngor version. That async error may be because of collision with newly introduced `async` keyword in python 3.5, but why in 3.8 ? That looks quite weird to me.

Can you show me the content of your `/home/theo/.local/lib/python3.8/site-packages/clyngor/solving.py` and your `/home/theo/.local/lib/python3.8/site-packages/clyngor/__init__.py` ?

Anyway, thank you for reporting that problem.

As you can see, i don't have much time for clyngor, but i would really like to continue working on it.

**Comment by bradleypallen** [comment] 2022-02-02 00:13
Running into the same issue, this time in 3.9 as well as 3.8.

**Comment by arnicas** [comment] 2022-02-21 13:33
I have it in 3.7.

**Comment by Aluriak** [comment] 2022-02-21 14:01
(OMG It's invading lower levels !)

I tried a fix ; looking at the new clingo API, `async` keyword is now `async_`, which have been changed in the source code.
Can you please test this ?

**Comment by arnicas** [comment] 2022-02-21 14:14
Really sorry..  Now I get this:

`
>>> from clyngor import ASP, solve
>>> answers = ASP("""
... rel(a,(c;d)). rel(b,(d;e)).
... obj(X):- rel(X,_) ; rel(X,Y): att(Y).
... att(Y):- rel(_,Y) ; rel(X,Y): obj(X).
... :- not obj(X):obj(X).
... :- not att(Y):att(Y).
... """)
>>> for answer in answers:
...     print(answer)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/clyngor/answers.py", line 205, in __iter__
    for answer_set, optimization, optimality, answer_number in self._answers:
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/clyngor/answers.py", line 330, in __compute_answers
    for a in model.symbols(shown=True))
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/clyngor/answers.py", line 330, in <genexpr>
    for a in model.symbols(shown=True))
  File "/Users/cherny/miniconda3/envs/pandasnlp/lib/python3.7/site-packages/clyngor/utils.py", line 131, in clingo_symbol_as_python_value
    "".format(value, type(value)))
NameError: name 'value' is not defined
`

**Comment by Aluriak** [comment] 2022-02-21 14:41
Thank you for testing that !
I start to see that clingo API has changed a lot.

I will dig into that before the end of the week.

**Comment by Aluriak** [comment] 2022-02-27 18:06
Hi !
I've upgraded clyngor to 0.4.1 to handle the new clingo module API. Please test again your code, to see if there is still a problem.

**Comment by arnicas** [comment] 2022-02-28 12:00
hi - that runs the doc example, thank you very much!

**Comment by Aluriak** [comment] 2022-02-28 17:13
\o/

I will close this issue then ; do not hesitate to reopen it if the problem arise again.

**Closed by Aluriak** 2022-02-28 17:13 UTC
